### ISSUE TITLE
Consider renaming the default branch to `main`

### ISSUE THREAD

**Issue by nrempel** [masalachai/epp-client#12]
The git ecosystem is moving away from `master` to `main` for the name of the default branch. Would you consider renaming the default branch? GitHub makes this pretty easy I think: https://github.com/github/renaming#renaming-existing-branches

https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by masalachai** [comment]
Yeah we can do that 👍

**Comment by masalachai** [comment]
Hi @nrempel and @djc ,

The default branch has been renamed to main

**Comment by djc** [comment]
Great, thanks! (I guess this can be closed now.)

**Comment by nrempel** [comment]
🎉
